# Generated by Django 6.0.3 on 2026-03-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_facultyprofile_delete_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='image',
            field=models.ImageField(blank=True, default='faculty/default.png', null=True, upload_to='faculty/'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
