# Generated by Django 6.0.3 on 2026-03-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_facultyprofile_image_facultyprofile_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
