# Generated by Django 6.0.3 on 2026-03-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='resources/')),
                ('type', models.CharField(choices=[('notes', 'Notes'), ('timetable', 'Timetable'), ('results', 'Results')], max_length=20)),
            ],
        ),
    ]
